version: '2'

services:
  cats:
    build:
      context: .
      dockerfile: ./apps/cats/Dockerfile
    command: npm run start:dev cats
    env_file:
      - ./apps/cats/.dev.env
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      -  '3000:3000'

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./database-data:/data/db

  mongodb-express:
    image: mongo-express:latest
    container_name: mongodb-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
